name: Android CI

on:
  push:
    branches: [ main, "hu/**" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Show Gradle version
        run: ./gradlew --version

      - name: Build (debug)
        run: ./gradlew assembleDebug --stacktrace
